### ISSUE TITLE
Feature: User can create a password protected profile

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDrop#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can register an account with eggDROP. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user navigates to eggDROP, they can create an account to login. 

## 🖼️ Wireframes

<img width="340" alt="Screen Shot 2021-12-11 at 11 07 19 AM" src="https://user-images.githubusercontent.com/88848572/145688605-16aae3d9-0bc0-439d-b492-b9d413c2fcba.png">

![Screen Shot 2021-12-11 at 11 26 10 AM](https://user-images.githubusercontent.com/88848572/145689091-78bfe53c-4e14-4fe8-9a73-ff75324e5468.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to include users table
- [ ] Update `data.sql` to include new user

### ☁️ Server

- [ ] Update `server/index.js` to add user table
- [ ] Update `server/index.js` to add new user
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to collect user input

### 🧑‍⚕️ Clean Up

- [ ] Make login page and style appropriately
- [ ] Test user input and ensure it's writing to database. 
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
