### ISSUE TITLE
Feature 2: User can drop an egg at their desired location 

### ISSUE THREAD

**Issue by mpowers1113** [mpowers1113/eggDrop#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can drop an egg at their desired location, whether it’s their current location or another one.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Within the main page (map), the user can navigate to a location of their choosing and drop an egg. The egg will stay fixed at that location for others to pick up. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-12-11 at 11 31 17 AM](https://user-images.githubusercontent.com/88848572/145689218-735f2369-beeb-4fc8-8506-f9c218bfeb55.png)
![Screen Shot 2021-12-11 at 11 46 56 AM](https://user-images.githubusercontent.com/88848572/145689690-cae426de-f883-4925-9e95-6c0616da3ac8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to include user location, eggData, and the following rows that can be viewed here: https://dbdesigner.page.link/b1qXPXwTJ8Wfs7RQ9
- [ ] Update `data.sql` to include the aforementioned tables

### ☁️ Server

- [ ] Update `server/index.js` to fetch userData and eggData
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to add the egg.
- [ ] Update main map to include added egg. 

### 🧑‍⚕️ Clean Up

- [ ] Create main page map. 
- [ ] Create component to add egg. 
- [ ] Update main page to include added egg. 
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
